/**
 * Created with IntelliJ IDEA.
 * User: stpyang
 * Date: 12/6/13
 * Time: 11:12 AM
 * To change this template use File | Settings | File Templates.
 */
public class Problem002 implements MySolution {

    private final int N;

    public Problem002(int n) {
        N = n;
    }

    // the even terms in the Fibonacci sequence are generated by the seque ce
    // e_0 = 0, e_1 = 2, and e_{n + 1} = 4 * e_n + e_{n - 1}
    @SuppressWarnings("WeakerAccess")
    public long solve() {

        long result = 2;
        int a = 0;
        int b = 2;

        while (true) {
            int c = 4 * b + a;
            if (c >= N) break;
            result += c;
            a = b;
            b = c;
        }

        return result;
    }

    public static void main(String[] args) {
        System.out.println(new Problem002(400000).solve());
    }
}
